### ISSUE TITLE
Release Windows Executable

### ISSUE THREAD

**Issue by utkuozdemir** [a0s/nvidia-smi-exporter#8]
Hi,

Great project!

Since nvidia-smi is a binary that is also available on Windows, this project can potentially run without any issues on a Windows system. It would be great to have a Windows binary (using ruby-packer or something) or an installer, so that regular gaming PCs etc can have their metrics exported.

Sharing Nvidia GPUs with Docker for Windows is still experimental, and there shouldn't be a need to run Docker at all.

Would you consider providing pre-built executables on releases? Not only for Windows but for other OSes as well?

**Comment by utkuozdemir** [comment]
Update on this: I am currently building a very similar nvidia-smi based exporter in Go. Will make it public pretty soon. So you decide to drop the topic, if you wish.

**Comment by a0s** [comment]
@utkuozdemir  Yep, i tried build exporter with `rubyc` (for Mac), and what i've got after running:

```
./a.out
Traceback (most recent call last):
        6: from /__enclose_io_memfs__/local/app/application.rb:2:in `<main>'
        5: from /__enclose_io_memfs__/local/app/application.rb:2:in `require_relative'
        4: from /__enclose_io_memfs__/local/app/exporter.rb:3:in `<top (required)>'
        3: from /__enclose_io_memfs__/local/app/exporter.rb:3:in `require_relative'
        2: from /__enclose_io_memfs__/local/app/n_vidia_smi_xml.rb:2:in `<top (required)>'
        1: from /__enclose_io_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:155:in `require'
/__enclose_io_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:155:in `require': cannot load such file -- nokogiri (LoadError)
        13: from /__enclose_io_memfs__/local/app/application.rb:2:in `<main>'
        12: from /__enclose_io_memfs__/local/app/application.rb:2:in `require_relative'
        11: from /__enclose_io_memfs__/local/app/exporter.rb:3:in `<top (required)>'
        10: from /__enclose_io_memfs__/local/app/exporter.rb:3:in `require_relative'
         9: from /__enclose_io_memfs__/local/app/n_vidia_smi_xml.rb:2:in `<top (required)>'
         8: from /__enclose_io_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:156:in `require'
         7: from /__enclose_io_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `rescue in require'
         6: from /__enclose_io_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `require'
         5: from /__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/nokogiri-1.11.4-x86_64-darwin/lib/nokogiri.rb:11:in `<top (required)>'
         4: from /__enclose_io_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:103:in `require'
         3: from /__enclose_io_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:103:in `require'
         2: from /__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/nokogiri-1.11.4-x86_64-darwin/lib/nokogiri/extension.rb:6:in `<top (required)>'
         1: from /__enclose_io_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:155:in `require'
/__enclose_io_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:155:in `require': cannot load such file -- nokogiri/2.7/nokogiri (LoadError)
        14: from /__enclose_io_memfs__/local/app/application.rb:2:in `<main>'
        13: from /__enclose_io_memfs__/local/app/application.rb:2:in `require_relative'
        12: from /__enclose_io_memfs__/local/app/exporter.rb:3:in `<top (required)>'
        11: from /__enclose_io_memfs__/local/app/exporter.rb:3:in `require_relative'
        10: from /__enclose_io_memfs__/local/app/n_vidia_smi_xml.rb:2:in `<top (required)>'
         9: from /__enclose_io_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:156:in `require'
         8: from /__enclose_io_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `rescue in require'
         7: from /__enclose_io_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `require'
         6: from /__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/nokogiri-1.11.4-x86_64-darwin/lib/nokogiri.rb:11:in `<top (required)>'
         5: from /__enclose_io_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:103:in `require'
         4: from /__enclose_io_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:103:in `require'
         3: from /__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/nokogiri-1.11.4-x86_64-darwin/lib/nokogiri/extension.rb:4:in `<top (required)>'
         2: from /__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/nokogiri-1.11.4-x86_64-darwin/lib/nokogiri/extension.rb:25:in `rescue in <top (required)>'
         1: from /__enclose_io_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:155:in `require'
/__enclose_io_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:155:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)
``` 

I think it takes too much effort. And it's just pointless.
